version: '3.4'

services:

  mysql:
    image: mysql:8.0
    container_name: mp_mysql
    ports:
      - 3306:3306
    volumes:
      - /var/docker_persistant_data/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: simon1001
      MYSQL_DATABASE: mp_shop
      MYSQL_USER: simon
      MYSQL_PASSWORD: simon1001
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--protocol=tcp", "-p123456"]
      timeout: 20s
      interval: 10s
      retries: 20

  redis:
    image: redis:6.2
    container_name: mp_redis
    volumes:
      - ./var/docker_persistant_data/redis:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6379:6379
    command: redis-server --requirepass simon1001
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      interval: 10s
      retries: 20

  nginxWebUi-server:
    image: cym1102/nginxwebui:latest
    container_name: nginx_server
    volumes:
      - /home/nginxWebUI:/home/nginxWebUI
    environment:
      BOOT_OPTIONS: "--server.port=8080"
    privileged: true
    network_mode: "host"

  staticfiles:
    image: nginx
    container_name: image_static
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /mnt/static_volume:/var/mapped
    ports:
      - "8004:80"

  api:
    depends_on:
      - mysql
    image: ghcr.io/villageflower/mp_simon:latest
    container_name: mp_api
    volumes:
      - /mnt/static_volume:/data
    ports:
      - 8888:8888
    environment:
        db_url  : jdbc:mysql://mysql:3306/mp_shop?createDatabaseIfNotExist=true&serverTimezone=Asia/Singapore
        db_username : simon
        db_password : simon1001



  admin:
    image: ghcr.io/villageflower/mp_admin:latest
    container_name: mp_admin
    ports:
      - 8898:80

